// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI4NApdso6wgILHvZ9SOQjoUIstbX3WNM',
    appId: '1:143463233680:web:1409cc3aee5fde98504015',
    messagingSenderId: '143463233680',
    projectId: 'lastcoffee-1b8a3',
    authDomain: 'lastcoffee-1b8a3.firebaseapp.com',
    databaseURL: 'https://lastcoffee-1b8a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lastcoffee-1b8a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTraXEG9zf1teo9PaEr1_kev3pWBuJ5l0',
    appId: '1:143463233680:android:ed7173bdd366bf36504015',
    messagingSenderId: '143463233680',
    projectId: 'lastcoffee-1b8a3',
    databaseURL: 'https://lastcoffee-1b8a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lastcoffee-1b8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPlTv3Tt6r-XTJbtKstZ74R6DsQJ_74k',
    appId: '1:143463233680:ios:ac740470c9dc1e66504015',
    messagingSenderId: '143463233680',
    projectId: 'lastcoffee-1b8a3',
    databaseURL: 'https://lastcoffee-1b8a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lastcoffee-1b8a3.appspot.com',
    iosClientId: '143463233680-3hv83vpo0trk1emvmg126mlflm9c1cum.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastcoffe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfPlTv3Tt6r-XTJbtKstZ74R6DsQJ_74k',
    appId: '1:143463233680:ios:ac740470c9dc1e66504015',
    messagingSenderId: '143463233680',
    projectId: 'lastcoffee-1b8a3',
    databaseURL: 'https://lastcoffee-1b8a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lastcoffee-1b8a3.appspot.com',
    iosClientId: '143463233680-3hv83vpo0trk1emvmg126mlflm9c1cum.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastcoffe',
  );
}
